repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-toml
        name: Check toml syntax
      - id: check-yaml
        name: Check yaml syntax
      - id: check-added-large-files
      - id: check-merge-conflict
        args: [--assume-in-merge]
        exclude: api.rst
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
        name: Format with black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.0
    hooks:
      - id: isort
        name: Order imports with isort
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: Lint with flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions, flake8-quotes, pep8-naming]
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: Check docstring style with pydocstyle
        exclude: tests
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        name: Check types with mypy
        additional_dependencies: [types-PyYAML, types-toml]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.376
    hooks:
    - id: pyright
      name: Check types with pyright
      additional_dependencies: [jax_dataclasses, hydra-core]
      args: ['src/deepqmc']
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      name: Check spelling
      args: ['--ignore-words', '.codespellignore']
