[build-system]
requires = ['setuptools>=61', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = 'deepqmc'
version = '1.2.0'
description = 'Deep-learning quantum Monte Carlo for electrons in real space'
authors = [
    {name = "Jan Hermann"},
    {name = "Zeno Schätzle", email = "zeno.schaetzle@fu-berlin.de"},
    {name = "Péter Bernát Szabó", email = "peter.bernat.szabo@fu-berlin.de"},
]
maintainers = [
    {name = "Zeno Schätzle", email = "zeno.schaetzle@fu-berlin.de"},
    {name = "Péter Bernát Szabó", email = "peter.bernat.szabo@fu-berlin.de"},
]
readme = 'README.md'
license = {text = 'MIT'}
classifiers = [
    'Development Status :: 4 - Beta',
    'Environment :: Console',
    'Environment :: GPU :: NVIDIA CUDA',
    'Intended Audience :: Science/Research',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: POSIX :: Linux',
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
    'Topic :: Scientific/Engineering :: Chemistry',
    'Topic :: Scientific/Engineering :: Physics',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
]
requires-python = ">=3.12"
dependencies = [
    'dm-haiku',
    'folx',
    'h5py',
    'hydra-core',
    'jax<0.9.0',
    'jaxlib',
    'jax-dataclasses',
    'kfac-jax',
    'scipy',
    'optax',
    'pyscf',
    'tensorboardX',
    'pyyaml',
    'tqdm',
    'uncertainties',
    'chex<1.0.0',
    'jaxtyping'
]

[project.optional-dependencies]
dev = [
    'pytest',
    'pytest-regressions',
    'pytest-cov',
    'black',
    'codespell',
    'pep8-naming',
    'pre-commit',
    'pydocstyle',
    'pyright',
]
doc = [
    'sphinx',
    'Jinja2',
    'sphinxcontrib-katex',
    'toml',
    'docutils',
    'pydata-sphinx-theme',
    'nbsphinx',
]
notebooks = [
    'jupyter',
    'ipykernel',
]

[project.urls]
homepage = 'https://deepqmc.github.io'
repository = 'https://github.com/deepqmc/deepqmc'
documentation = 'https://deepqmc.github.io'

[project.scripts]
deepqmc = 'deepqmc.app:cli'

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.yaml"]

[tool.black]
target-version = ['py312']
skip-string-normalization = true
preview = true

[tool.ruff.lint]
ignore = ["E741", "E731"]

[tool.ruff.lint.per-file-ignores]
"src/deepqmc/types.py" = ["F821"]

[tool.pyright]
include = ["src"]
typeCheckingMode = "standard"
pythonVersion = "3.12"
useLibraryCodeForTypes = true
reportGeneralTypeIssues = "error"
reportOptionalMemberAccess = "warning"
reportOptionalSubscript = "warning"
reportOptionalCall = "warning"
reportUnusedImport = "error"
reportUnusedVariable = "error"
reportMissingImports = "error"
