defaults:
  - _self_
  - optional .@_here_: deepqmc
  - task: train
  - ansatz: default
  - hamil: qc
  - override hydra/job_logging: custom
  - override hydra/help: custom
hydra:
  job:
    name: deepqmc
    chdir: true
  searchpath:
    - file://conf
  output_subdir: ${mode_subdir:}${process_idx_suffix:}/.hydra
task:
  workdir: ???
logging:
  deepqmc: 10
  jax: 40
  kfac: 40
