defaults:
  - _self_
  - optional .@_here_: deepqmc
  - task: train
  - ansatz: paulinet
  - hamil: qc
  - override hydra/job_logging: custom
  - override hydra/help: custom
hydra:
  job:
    name: deepqmc
    chdir: true
  searchpath:
    - file://conf
task:
  workdir: ???
device: cuda
