_target_: deepqmc.wf.paulinet.omni.OmniSchNet
_partial_: true
embedding_dim: 128
jastrow: many-body
jastrow_factory:
  _target_: deepqmc.wf.paulinet.omni.Jastrow
  _partial_: true
  n_layers: 3
  sum_first: true
backflow: many-body
backflow_factory:
  _target_: deepqmc.wf.paulinet.omni.Backflow
  _partial_: true
  n_layers: 3
schnet_factory:
  _target_: deepqmc.wf.paulinet.schnet.ElectronicSchNet
  _partial_: true
  dist_basis: null
  dist_feat_dim: 32
  dist_feat_cutoff: 10.0
  dist_basis_envelope: nocusp
  n_interactions: 3
  kernel_dim: 64
  version: 2
  layer_norm: false
  use_diffs: false
  initial_embedding: embedding
  subnet_metafactory:
    _target_: deepqmc.wf.paulinet.schnet.SubnetFactory
    _partial_: true
    n_layers_w: 2
    n_layers_h: 1
    n_layers_g: 1
