submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 20160
cpus_per_task: null
gpus_per_node: 1
tasks_per_node: 1
mem_gb: null
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: ???
qos: null
comment: null
constraint: null
exclude: null
gres: null
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
mem_per_cpu: null
account: null
signal_delay_s: 2
max_num_timeout: 0
additional_parameters: {}
array_parallelism: 256
setup: null
srun_args: null
