defaults:
  - _self_
  - optional .@_here_: deepqmc
  - task: qho
  - override hydra/job_logging: custom
hydra:
  job:
    name: deepqmc
    chdir: true
  searchpath:
    - file://conf
task:
  _target_: deepqmc.jax.app.train_from_factories
  workdir: ???
  seed: 0
