defaults:
  - _self_
  - optional .@_here_: deepqmc
  - task: train
  - override hydra/job_logging: custom
hydra:
  job:
    name: deepqmc
    chdir: true
  searchpath:
    - file://conf
task:
  workdir: ???
