_target_: deepqmc.gnn.edge_features.CombinedRadialBases
_partial_: true
factories:
- _target_: deepqmc.gnn.edge_features.GaussianBasis
  _partial_: true
  offset: true
  envelope_factory:
    _target_: deepqmc.gnn.edge_features.PolynomialEnvelope
    _partial_: true
    n0: 0
    n1: 2
- _target_: deepqmc.gnn.edge_features.DistancePowersBasis
  _partial_: true
  powers: [1]
  envelope_factory:
    _target_: deepqmc.gnn.edge_features.PolynomialEnvelope
    _partial_: true
    n0: 0
    n1: 2
n_rbfs: [31, 1]
