_target_: deepqmc.jax.gnn.edge_features.CombinedRadialBases
_partial_: true
factories:
- _target_: deepqmc.jax.gnn.edge_features.GaussianBasis
  _partial_: true
- _target_: deepqmc.jax.gnn.edge_features.DistancePowersBasis
  _partial_: true
  powers: [1]
n_rbfs: [15, 1]
