_target_: deepqmc.app.train_from_checkpoint
evaluate: true
keep_sampler_state: true
restdir: ???
observable_monitors:
  - _target_: deepqmc.observable.ACZVQForceMonitor
    save_samples: True
    period: 1
  - _target_: deepqmc.observable.ACZVForceMonitor
    save_samples: True
    period: 1
  - _target_: deepqmc.observable.ACZVZBQForceMonitor
    save_samples: True
    period: 1
  - _target_: deepqmc.observable.ACZVZBForceMonitor
    save_samples: True
    period: 1
h5_logger:
  _target_: deepqmc.log.H5Logger
  _partial_: true
  keys_whitelist:
    - mol_idxs
    - local_energy
    - time
    - step
    - hf_force_bare
    - hf_force_ac_zv
    - hf_force_ac_zvq
    - hf_force_ac_zvzb
    - hf_force_ac_zvzbq
