defaults:
  - sampler: decorr_metropolis
  - opt: kfac
_target_: deepqmc.app.train_from_factories
hamil: ${hamil}
ansatz: ${ansatz}
steps: 1000
sample_size: 1000
seed: 0
fit_kwargs:
  clip_mask_fn:
    _target_: deepqmc.fit.median_clip_and_mask
    _partial_: true
    clip_width: 5
    median_center: true
