defaults:
  - sampler: metropolis_saml
  - opt: kfac
_target_: deepqmc.app.train_from_factories
hamil: ${hamil}
ansatz: ${ansatz}
steps: 50000
molecule_batch_size: 1
electron_batch_size: 2048
seed: 0
pretrain_steps: 5000
pretrain_kwargs:
  opt: adam
  opt_kwargs:
    learning_rate: 3.e-4
    b1: 0.9
    b2: 0.999
  baseline_kwargs:
    basis: 6-311G
fit_kwargs:
  clip_mask_fn:
    _target_: deepqmc.clip.median_clip_and_mask
    _partial_: true
    clip_width: 5.0
    median_center: false
