defaults:
  - sampler_factory: decorr_langevin
  - opt: kfac
_target_: deepqmc.app.train_from_factories
hamil: ${hamil}
ansatz: ${ansatz}
steps: 1000
molecule_batch_size: 1
electron_batch_size: 1000
electronic_states: 1
seed: 0
pretrain_steps: 100
pretrain_kwargs:
  opt: adam
  opt_kwargs:
    learning_rate: 3.e-4
    b1: 0.9
    b2: 0.999
  scf_kwargs:
    basis: sto-6g
loss_function_factory:
  _target_: deepqmc.loss.create_loss_fn
  _partial_: true
  alpha: 4.0
  clip_mask_fn:
    _target_: deepqmc.loss.median_log_squeeze_and_mask
    _partial_: true
  clip_mask_overlap_fn:
    _target_: deepqmc.loss.psi_ratio_clip_and_mask
    _partial_: true
mols:
  _target_: deepqmc.app.read_molecules
  directory: null
metric_logger_constructor:
  _target_: deepqmc.log.TensorboardMetricLogger
  _partial_: true
  max_queue: 10
chkpt_constructor:
  _target_: deepqmc.log.CheckpointStore
  _partial_: true
h5_logger_constructor:
  _target_: deepqmc.log.H5Logger
  _partial_: true
  keys_whitelist:
    - local_energy
