defaults:
  - sampler: decorr_metropolis_psiformer
  - opt: kfac_psiformer
_target_: deepqmc.app.train_from_factories
hamil: ${hamil}
ansatz: ${ansatz}
steps: 200000
molecule_batch_size: 1
electron_batch_size: 4096
pretrain_steps: 20000
pretrain_kwargs:
  opt: lamb
  opt_kwargs:
    learning_rate: 3.e-4
    b1: 0.9
    b2: 0.999
  baseline_kwargs:
    basis: sto-6g
seed: 0
fit_kwargs:
  clip_mask_fn:
    _target_: deepqmc.clip.median_clip_and_mask
    _partial_: true
    clip_width: 5
    median_center: true
metric_logger:
  _target_: deepqmc.log.TensorboardMetricLogger
  _partial_: true
  period: 10
mols:
  _target_: deepqmc.app.read_molecules
  directory: null
