defaults:
  - sampler: decorr_metropolis
_target_: deepqmc.app.train_from_factories
hamil: ${hamil}
ansatz: ${ansatz}
nuc_configs:
  _target_: deepqmc.app.nuclear_configurations
  data: ${hamil.mol.data}
opt: kfac
steps: 1000
sample_size: 1000
seed: 0
