_target_: deepqmc.wf.NeuralNetworkWaveFunction
_partial_: true
envelope:
  _target_: deepqmc.wf.nn_wave_function.env.ExponentialEnvelopes
  _partial_: true
  isotropic: true
  per_shell: false
  per_orbital_exponent: true
  spin_restricted: false
  init_to_ones: true
  softplus_zeta: true
backflow_op:
  _target_: deepqmc.wf.nn_wave_function.nn_wave_function.BackflowOp
  _partial_: true
  mult_act: '${eval:"lambda x: x"}'
n_determinants: 32
full_determinant: true
cusp_electrons: false
cusp_alpha_electrons: null
cusp_nuclei: false
cusp_alpha_nuclei: null
backflow_transform: mult
conf_coeff:
  _target_: deepqmc.hkext.SumPool
  _partial_: true
omni_factory:
  _target_: deepqmc.wf.nn_wave_function.omni.OmniNet
  _partial_: true
  embedding_dim: 256
  jastrow_factory: null
  backflow_factory:
    _target_: deepqmc.wf.nn_wave_function.omni.Backflow
    _partial_: true
    subnet_factory:
      _target_: deepqmc.hkext.MLP
      _partial_: true
      hidden_layers: ['log', 1]
      bias: false
      last_linear: true
      activation:
        _target_: deepqmc.hkext.ssp
        _partial_: true
      init: deeperwin
  gnn_factory:
    _target_: deepqmc.gnn.ElectronGNN
    _partial_: true
    n_interactions: 4
    positional_electron_embeddings: true
    two_particle_stream_dim: 32
    nuclei_embedding:
      _target_: deepqmc.gnn.electron_gnn.NucleiEmbedding
      _partial_: true
      embedding_dim: 32
      atom_type_embedding: true
      subnet_type: embed
    self_interaction: true
    edge_types:
    - same
    - anti
    - ne
    edge_features:
      ne:
        _target_: deepqmc.gnn.edge_features.CombinedEdgeFeature
        edge_features:
        - _target_: deepqmc.gnn.edge_features.DistancePowerEdgeFeature
          powers: [1]
        - _target_: deepqmc.gnn.edge_features.DifferenceEdgeFeature
      same:
        _target_: deepqmc.gnn.edge_features.DistancePowerEdgeFeature
        powers: [1]
      anti:
        _target_: deepqmc.gnn.edge_features.DistancePowerEdgeFeature
        powers: [1]
    layer_factory:
      _target_: deepqmc.gnn.electron_gnn.ElectronGNNLayer
      _partial_: true
      subnet_factory:
        _target_: deepqmc.hkext.MLP
        _partial_: true
        hidden_layers: ['log', 1]
        bias: true
        last_linear: false
        activation:
          _target_: jax.numpy.tanh
          _partial_: true
        init: deeperwin
      one_particle_residual: false
      two_particle_residual:
        _target_: deepqmc.hkext.ResidualConnection
        normalize: true
      convolution: true
      deep_features: separate
      mean_aggregate_edges: false
      update_rule: concatenate
      update_features: 
        - residual
        - node_up
        - node_down
        - convolution_ee
        - convolution_ne
      w_for_ne: false
