_target_: deepqmc.wf.NeuralNetworkWaveFunction
_partial_: true
envelope:
  _target_: deepqmc.wf.nn_wave_function.env.ExponentialEnvelopes
  _partial_: true
  isotropic: true
  per_shell: true
  per_orbital_exponent: true
  spin_restricted: false
backflow_op:
  _target_: deepqmc.wf.nn_wave_function.nn_wave_function.BackflowOp
  _partial_: true
n_determinants: 32
full_determinant: false
cusp_electrons: false
cusp_alpha: null
backflow_transform: mult
conf_coeff:
  _target_: deepqmc.hkext.SumPool
  _partial_: true
omni_factory:
  _target_: deepqmc.wf.nn_wave_function.omni.OmniNet
  _partial_: true
  embedding_dim: 256
  jastrow_factory: null
  backflow_factory:
    _target_: deepqmc.wf.nn_wave_function.omni.Backflow
    _partial_: true
    subnet_factory:
      _target_: deepqmc.hkext.MLP
      _partial_: true
      hidden_layers: ['log', 1]
      bias: false
      last_linear: true
      activation:
        _target_: deepqmc.hkext.ssp
        _partial_: true
      w_init: deeperwin
  gnn_factory:
    _target_: deepqmc.gnn.ElectronGNN
    _partial_: true
    n_interactions: 4
    positional_electron_embeddings: true
    atom_type_embeddings: true
    two_particle_stream_dim: 32
    edge_types:
    - same
    - anti
    - ne
    edge_features:
      ne:
        _target_: deepqmc.gnn.edge_features.CombinedEdgeFeature
        edge_features:
        - _target_: deepqmc.gnn.edge_features.DistancePowerEdgeFeature
          powers: [1]
        - _target_: deepqmc.gnn.edge_features.DifferenceEdgeFeature
      same:
        _target_: deepqmc.gnn.edge_features.DistancePowerEdgeFeature
        powers: [1]
      anti:
        _target_: deepqmc.gnn.edge_features.DistancePowerEdgeFeature
        powers: [1]
    layer_factory:
      _target_: deepqmc.gnn.electron_gnn.ElectronGNNLayer
      _partial_: true
      subnet_factory:
        _target_: deepqmc.hkext.MLP
        _partial_: true
        hidden_layers: ['log', 1]
        bias: true
        last_linear: false
        activation:
          _target_: jax.numpy.tanh
          _partial_: true
        w_init: deeperwin
      subnet_factory_by_lbl:
        w:
          _target_: deepqmc.hkext.MLP
          _partial_: true
          hidden_layers: ['log', 1]
          bias: false
          last_linear: false
          activation:
            _target_: jax.numpy.tanh
            _partial_: true
          w_init: deeperwin
      residual:
        _target_: deepqmc.hkext.ResidualConnection
        normalize: false
      convolution: true
      deep_features: separate
      update_rule: concatenate
      update_features: 
        - residual
        - node_up
        - node_down
        - edge_ee
        - edge_ne
