_target_: deepqmc.wf.NeuralNetworkWaveFunction
_partial_: true
envelope:
  _target_: deepqmc.wf.baseline.baseline.Baseline.from_mol
  _partial_: true
  is_baseline: true
backflow_op:
  _target_: deepqmc.wf.nn_wave_function.nn_wave_function.BackflowOp
  _partial_: true
n_determinants: 16
full_determinant: false
cusp_electrons:
  _target_: deepqmc.wf.nn_wave_function.cusp.ElectronicCuspAsymptotic
  _partial_: true
  same_scale: 0.25
  anti_scale: 0.5
  alpha: 10.0
  trainable_alpha: false
  cusp_function:
    _target_: deepqmc.wf.nn_wave_function.cusp.DeepQMCCusp
cusp_nuclei:
  _target_: deepqmc.wf.nn_wave_function.cusp.NuclearCuspAsymptotic
  _partial_: true
  alpha: 10.0
  trainable_alpha: false
  cusp_function:
    _target_: deepqmc.wf.nn_wave_function.cusp.DeepQMCCusp
backflow_transform: both
conf_coeff:
  _target_: haiku.Linear
  _partial_: true
  with_bias: false
  w_init:
    _target_: jax.numpy.ones
    _partial_: true
omni_factory:
  _target_: deepqmc.wf.nn_wave_function.omni.OmniNet
  _partial_: true
  embedding_dim: 64
  jastrow_factory: 
    _target_: deepqmc.wf.nn_wave_function.omni.Jastrow
    _partial_: true
    sum_first: true
    subnet_factory:
      _target_: deepqmc.hkext.MLP
      _partial_: true
      hidden_layers: ['log', 3]
      bias: 'not_last'
      last_linear: true
      activation:
        _target_: deepqmc.hkext.ssp
        _partial_: true
      init: default
  backflow_factory:  
    _target_: deepqmc.wf.nn_wave_function.omni.Backflow
    _partial_: true
    subnet_factory:
      _target_: deepqmc.hkext.MLP
      _partial_: true
      hidden_layers: ['log', 3]
      bias: true
      last_linear: true
      activation:
        _target_: deepqmc.hkext.ssp
        _partial_: true
      init: default
  gnn_factory:
    _target_: deepqmc.gnn.ElectronGNN
    _partial_: true
    n_interactions: 4
    electron_embedding:
      _target_: deepqmc.gnn.electron_gnn.ElectronEmbedding
      _partial_: true
      positional_embeddings: false
      use_spin: false
      project_to_embedding_dim: false
    nuclei_embedding:
      _target_: deepqmc.gnn.electron_gnn.NucleiEmbedding
      _partial_: true
      embedding_dim: 64
      atom_type_embedding: false
      subnet_type: embed
    two_particle_stream_dim: 64
    self_interaction: false
    edge_features:
      ne:
        _target_: deepqmc.gnn.edge_features.GaussianEdgeFeature
        n_gaussian: 16
        radius: 30
        offset: False
      same:
        _target_: deepqmc.gnn.edge_features.GaussianEdgeFeature
        n_gaussian: 16
        radius: 30
        offset: False
      anti:
        _target_: deepqmc.gnn.edge_features.GaussianEdgeFeature
        n_gaussian: 16
        radius: 30
        offset: False
    layer_factory:
      _target_: deepqmc.gnn.electron_gnn.ElectronGNNLayer
      _partial_: true
      subnet_factory:
        _target_: deepqmc.hkext.MLP
        _partial_: true
        hidden_layers: ['log', 3]
        bias: true
        last_linear: false
        activation:
          _target_: jax.numpy.tanh
          _partial_: true
        init: default
      one_particle_residual:
        _target_: deepqmc.hkext.ResidualConnection
        normalize: false
      two_particle_residual: false
      deep_features: false
      update_rule: featurewise
      update_features:
      - _target_: deepqmc.gnn.update_features.ConvolutionUpdateFeature
        _partial_: true
        edge_types: [same, anti, ne]
        normalize: false
        w_factory:
          _target_: deepqmc.hkext.MLP
          _partial_: true
          hidden_layers: ['log', 3]
          bias: false
          last_linear: false
          activation:
            _target_: jax.numpy.tanh
            _partial_: true
          init: default
        h_factory:
          _target_: deepqmc.hkext.MLP
          _partial_: true
          hidden_layers: ['log', 3]
          bias: true
          last_linear: false
          activation:
            _target_: jax.numpy.tanh
            _partial_: true
          init: default
  
