_target_: deepqmc.wf.NeuralNetworkWaveFunction
_partial_: true
envelope:
  _target_: deepqmc.wf.nn_wave_function.env.ExponentialEnvelopes.from_mol
  _partial_: true
  isotropic: true
backflow_op:
  _target_: deepqmc.wf.nn_wave_function.nn_wave_function.BackflowOp
  _partial_: true
n_determinants: 16
full_determinant: false
cusp_electrons: true
cusp_alpha: 10.0
backflow_transform: mult
omni_factory:
  _target_: deepqmc.wf.nn_wave_function.omni.OmniNet
  _partial_: true
  embedding_dim: 64
  jastrow_factory: 
    _target_: deepqmc.wf.nn_wave_function.omni.Jastrow
    _partial_: true
    sum_first: true
    subnet_kwargs: 
      hidden_layers: ['log', 3]
      last_linear: true
      bias: 'not_last'
      activation: 
        _target_: deepqmc.hkext.ssp
        _partial_: true
  backflow_factory:  
    _target_: deepqmc.wf.nn_wave_function.omni.Backflow
    _partial_: true
    subnet_kwargs:
      hidden_layers: ['log', 3]
      last_linear: true
      activation:
        _target_: deepqmc.hkext.ssp
        _partial_: true
  gnn_factory:
    _target_: deepqmc.gnn.ElectronGNN
    _partial_: true
    n_interactions: 4
    positional_electron_embeddings: false
    atom_type_embeddings: false
    edge_features:
      _target_: deepqmc.gnn.edge_features.CombinedEdgeFeature
      edge_features:
      - _target_: deepqmc.gnn.edge_features.DistancePowerEdgeFeature
        powers: [1]
      - _target_: deepqmc.gnn.edge_features.DifferenceEdgeFeature
    layer_kwargs:
      subnet_kwargs:
        hidden_layers: ['log', 3]
        last_linear: false
        activation: 
          _target_: jax.numpy.tanh
          _partial_: true
      subnet_kwargs_by_lbl: null
      residual: true
      convolution: true
      deep_features: false
      update_rule: featurewise
      update_features: 
        - same
        - anti
        - ne
  
