_target_: deepqmc.wf.NeuralNetworkWaveFunction
_partial_: true
envelope:
  _target_: deepqmc.wf.nn_wave_function.env.ExponentialEnvelopes
  _partial_: true
  isotropic: true
  per_shell: true
  per_orbital_exponent: false
  spin_restricted: true
  init_to_ones: false
  softplus_zeta: false
backflow_op:
  _target_: deepqmc.wf.nn_wave_function.nn_wave_function.BackflowOp
  _partial_: true
n_determinants: 16
full_determinant: false
cusp_electrons: true
cusp_alpha: 10.0
backflow_transform: mult
conf_coeff:
  _target_: haiku.Linear
  _partial_: true
  with_bias: false
  w_init:
    _target_: jax.numpy.ones
    _partial_: true
omni_factory:
  _target_: deepqmc.wf.nn_wave_function.omni.OmniNet
  _partial_: true
  embedding_dim: 64
  jastrow_factory: 
    _target_: deepqmc.wf.nn_wave_function.omni.Jastrow
    _partial_: true
    sum_first: true
    subnet_factory:
      _target_: deepqmc.hkext.MLP
      _partial_: true
      hidden_layers: ['log', 3]
      bias: 'not_last'
      last_linear: true
      activation:
        _target_: deepqmc.hkext.ssp
        _partial_: true
      init: default
  backflow_factory:  
    _target_: deepqmc.wf.nn_wave_function.omni.Backflow
    _partial_: true
    subnet_factory:
      _target_: deepqmc.hkext.MLP
      _partial_: true
      hidden_layers: ['log', 3]
      bias: true
      last_linear: true
      activation:
        _target_: deepqmc.hkext.ssp
        _partial_: true
      init: default
  gnn_factory:
    _target_: deepqmc.gnn.ElectronGNN
    _partial_: true
    n_interactions: 4
    positional_electron_embeddings: false
    nuclei_embedding:
      _target_: deepqmc.gnn.electron_gnn.NucleiEmbedding
      _partial_: true
      embedding_dim: 64
      atom_type_embedding: false
      subnet_type: embed
    two_particle_stream_dim: 64
    self_interaction: false
    edge_types:
    - same
    - anti
    - ne
    edge_features:
      ne:
        _target_: deepqmc.gnn.edge_features.CombinedEdgeFeature
        edge_features:
        - _target_: deepqmc.gnn.edge_features.DistancePowerEdgeFeature
          powers: [1]
        - _target_: deepqmc.gnn.edge_features.DifferenceEdgeFeature
      same:
        _target_: deepqmc.gnn.edge_features.CombinedEdgeFeature
        edge_features:
        - _target_: deepqmc.gnn.edge_features.DistancePowerEdgeFeature
          powers: [1]
        - _target_: deepqmc.gnn.edge_features.DifferenceEdgeFeature
      anti:
        _target_: deepqmc.gnn.edge_features.CombinedEdgeFeature
        edge_features:
        - _target_: deepqmc.gnn.edge_features.DistancePowerEdgeFeature
          powers: [1]
        - _target_: deepqmc.gnn.edge_features.DifferenceEdgeFeature
    layer_factory:
      _target_: deepqmc.gnn.electron_gnn.ElectronGNNLayer
      _partial_: true
      subnet_factory:
        _target_: deepqmc.hkext.MLP
        _partial_: true
        hidden_layers: ['log', 3]
        bias: true
        last_linear: false
        activation:
          _target_: jax.numpy.tanh
          _partial_: true
        init: default
      subnet_factory_by_lbl:
        w:
          _target_: deepqmc.hkext.MLP
          _partial_: true
          hidden_layers: ['log', 3]
          bias: false
          last_linear: false
          activation:
            _target_: jax.numpy.tanh
            _partial_: true
          w_init: default
      one_particle_residual:
        _target_: deepqmc.hkext.ResidualConnection
        normalize: false
      two_particle_residual: false
      convolution: true
      deep_features: false
      mean_aggregate_edges: false
      update_rule: featurewise
      update_features: 
        - edge_same
        - edge_anti
        - edge_ne
  
