_target_: deepqmc.wf.NeuralNetworkWaveFunction
_partial_: true
envelope:
  _target_: deepqmc.wf.nn_wave_function.env.ExponentialEnvelopes
  _partial_: true
  isotropic: true
  per_shell: false
  per_orbital_exponent: true
  spin_restricted: false
  init_to_ones: true
  softplus_zeta: false
backflow_op:
  _target_: deepqmc.wf.nn_wave_function.nn_wave_function.BackflowOp
  _partial_: true
  # mult_act: '${eval:"lambda x: x"}'
n_determinants: 16
full_determinant: true
cusp_electrons: true
cusp_alpha_electrons: 10
cusp_nuclei: false
cusp_alpha_nuclei: null
backflow_transform: mult
conf_coeff:
  _target_: deepqmc.hkext.SumPool
  _partial_: true
omni_factory:
  _target_: deepqmc.wf.nn_wave_function.omni.OmniNet
  _partial_: true
  embedding_dim: 256
  jastrow_factory: null
  backflow_factory:  
    _target_: deepqmc.wf.nn_wave_function.omni.Backflow
    _partial_: true
    subnet_factory:
      _target_: deepqmc.hkext.MLP
      _partial_: true
      hidden_layers: ['log', 1]
      bias: false
      last_linear: true
      activation: null
      init: ferminet
  gnn_factory:
    _target_: deepqmc.gnn.ElectronGNN
    _partial_: true
    n_interactions: 4
    spin_electron_embeddings: true
    positional_electron_embeddings:
      ne:
        _target_: deepqmc.gnn.edge_features.CombinedEdgeFeature
        edge_features:
        - _target_: deepqmc.gnn.edge_features.DistancePowerEdgeFeature
          powers: [1]
          log_rescale: true
        - _target_: deepqmc.gnn.edge_features.DifferenceEdgeFeature
          log_rescale: true
    nuclei_embedding: null
    two_particle_stream_dim: 32
    self_interaction: true
    edge_types: []
    edge_features: []
    layer_factory:
      _target_: deepqmc.gnn.electron_gnn.ElectronGNNLayer
      _partial_: true
      subnet_factory:
        _target_: deepqmc.hkext.Identity
        _partial_: true
      one_particle_residual:
        _target_: deepqmc.hkext.ResidualConnection
        normalize: false
      two_particle_residual: false
      deep_features: false
      update_rule: concatenate
      update_features: 
      - _target_: deepqmc.gnn.update_features.NodeAttentionUpdateFeature
        _partial_: true
  
