hamil:
  _target_: deepqmc.jax.hamil.qc.MolecularHamiltonian
  mol:
    _target_: deepqmc.jax.Molecule
    coords: [[0.0, 0.0, 0.0], [0.0, 0.0, 3.0141129518]]
    charges: [1, 3]
    charge: 0
    spin: 0
ansatz:
  _target_: deepqmc.jax.wf.PauliNet
  _partial_: true
opt:
  _target_: optax.adam
  learning_rate: 1e-3
sampler:
  - _target_: deepqmc.jax.sampling.DecorrSampler
    length: 10
  - _target_: deepqmc.jax.sampling.LangevinSampler
    _partial_: true
    tau: 1.0
steps: 1000
sample_size: 1000
clip_width: 1.0
