_target_: kfac_jax.Optimizer
_partial_: true
learning_rate_schedule:
  _target_: deepqmc.utils.InverseSchedule
  init_value: 0.01
  decay_rate: 5000
norm_constraint: 0.001
damping_schedule:
  _target_: deepqmc.utils.InverseSchedule
  init_value: 0.001
  decay_rate: 5000
