_target_: kfac_jax.Optimizer
_partial_: true
learning_rate_schedule:
  _target_: deepqmc.utils.InverseSchedule
  init_value: 0.05
  decay_rate: 100000
norm_constraint: 0.001
damping_schedule:
  _target_: deepqmc.utils.ConstantSchedule
  value: 0.001
