_target_: deepqmc.sampling.initialize_sampling
_partial_: true
elec_sampler:
  _target_: deepqmc.sampling.combine_samplers
  _partial_: true
  samplers:
    - _target_: deepqmc.sampling.DecorrSampler
      length: 10
    - _target_: deepqmc.sampling.LangevinSampler
      _partial_: true
      tau: 1.0
