_target_: deepqmc.sampling.combine_samplers
_partial_: true
samplers:
  - _target_: deepqmc.sampling.DecorrSampler
    length: 33
  - _target_: deepqmc.sampling.electron_samplers.OppositeSpinExchangeSampler
    exchange_step_probability: 0.1
  - _target_: deepqmc.sampling.MetropolisSampler
    _partial_: true
    tau: 1.0
    max_age: null
    sample_initializer:
      _target_: deepqmc.sampling.electron_sample_initializers.AtomCenteredElectronInitializer
      atom_centered_distribution:
        _target_: deepqmc.sampling.electron_sample_initializers.ShellBasedDistribution
