name: Documentation
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 1'
jobs:
  build:
    if: github.event_name != 'schedule' || github.repository == 'deepqmc/deepqmc'
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[doc]
      - name: Build
        run: sphinx-build -W -E doc doc/build
      - run: touch doc/build/.nojekyll
