name: pre-commit
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 1'


jobs:
  pre-commit:
    if: github.event_name != 'schedule' || github.repository == 'deepqmc/deepqmc'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
