name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 1'
jobs:
  all:
    if: github.event_name != 'schedule' || github.repository == 'deepqmc/deepqmc'
    name: All
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, '3.10']
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: echo YEAR_MONTH=$(date +"%Y-%m") >>$GITHUB_ENV
      - uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ env.YEAR_MONTH }}
      - name: Create Python virtual environment
        run: |
          python -m venv venv
          venv/bin/pip install -U pip wheel
          echo $PWD/venv/bin >>$GITHUB_PATH
      - name: Install
        run: pip install -e .[test] -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
      - name: Test
        run: coverage run -m pytest
      - name: Upload to Codecov
        run: bash <(curl -s https://codecov.io/bash)
